### ISSUE TITLE
enums are ignored when running example code

### ISSUE THREAD

**Issue by alexclaydon** [pchunduri6/rag-demystified#3]
Hello, thanks for a very nice low-dependency write-up on an important topic.  I came here from your comment on HN.

I spent yesterday playing around with your example code - both running it as it is and riffing off it with my own data and models - and am seeing the model fail to observe the constraints set by enums, leading to consistent (not just intermittent) Pydantic validation errors.  In each case, the failure mode is the same: Pydantic validation errors on the enum field. It's trying to use made-up function names instead of those specified in the enum.

I'm on Python 3.11.6, instructor 0.2.8, pydantic_2.4.2 and pydantic_core 2.10.1. I tried executing both through a Jupyter notebook and as a script from the command line.

Appreciate any guidance you might be able to provide! Please let me know if there's any additional information I can provide which would be helpful.

**Comment by pchunduri6** [comment]
Hi @alexclaydon, thanks for trying the codebase out! To help me look into it, can you share an example pydantic model definition that you tried, the expected output, and the actual output from the LLM? Thanks!
